name: Build Kernel
on: push

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-18
    steps:
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Build kernel
      run: |
        git clone https://github.com/oops-yu/test
        sudo apt install repo
        mkdir kernel 
        cd kernel
        repo init -u https://android.googlesource.com/kernel/manifest
        mv ../test/my.xml ./.repo/manifests/my.xml
        repo init -m my.xml
        repo sync -j8 



    

    

    