name: Build Kernel
on: push

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-20.04
    steps:
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Build kernel
      run: |
        git clone https://github.com/oops-yu/test
        cd test
        chmod a+x env.sh
        ./env.sh
        export PATH=~/bin:$PATH
        cd kernel
        repo sync -j8 



    

    

    