name: Build Kernel
on: push

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Build kernel
      run: |
        mkdir ~/bin
        mkdir ~/out
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        cd ~
        export PATH=~/bin:$PATH
        git clone https://github.com/oops-yu/test
        mkdir kernel 
        cd kernel
        repo init -u https://android.googlesource.com/kernel/manifest
        mv ../test/my.xml ./.repo/manifests/my.xml
        repo init -m my.xml
        repo sync 
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        LTO=thin tools/bazel build --config=fast //common:kernel_aarch64

    - name: Upload KernelImg
      uses: actions/upload-artifact@v3
      with:
        name: Kernel
        path: ~/kernel/bazel-bin/common/kernel_aarch64/Image




    

    

    